# Generated by Django 4.0.4 on 2022-05-30 06:06

from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(null=True, upload_to=shop.models.get_file_path)),
                ('description', models.TextField(max_length=400)),
                ('trending', models.BooleanField(default=False, help_text='0 = default ,  1= Trending ')),
                ('meta_title', models.CharField(max_length=100)),
                ('meta_keywords', models.CharField(max_length=100)),
                ('meta_description', models.TextField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('product_image', models.ImageField(null=True, upload_to=shop.models.get_file_path)),
                ('description', models.CharField(max_length=400)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('discount', models.FloatField()),
                ('trending', models.BooleanField(default=False, help_text='0 = default ,  1= Trending ')),
                ('meta_title', models.CharField(max_length=100)),
                ('meta_keywords', models.CharField(max_length=100)),
                ('meta_description', models.TextField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
        ),
    ]
