# Generated by Django 4.0.4 on 2022-05-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('category', models.CharField(choices=[('Juice', 'Juice'), ('Alcohol', 'Alcohol'), ('Soda', 'Soda'), ('Cocktail', 'Cocktail'), ('Fresh', 'Fresh Juices'), ('Energy', 'Energy Drinks'), ('E', 'Beddings')], max_length=20)),
            ],
        ),
    ]
