# Generated by Django 4.0.4 on 2022-05-25 13:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Juice', 'Juice'), ('Alcohol', 'Alcohol'), ('Soda', 'Soda'), ('Cocktail', 'Cocktail'), ('Fresh', 'Fresh Juices'), ('Energy', 'Energy Drinks')], max_length=20),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('completed', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth.customer')),
            ],
        ),
    ]
